"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['hitunGUI.py']
APP_NAME = 'HitunCheckin'
DATA_FILES = []
OPTIONS = {
    'iconfile': 'hitun.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
